version: '3.8'

services:
  app:
    build:
      context: .
      target: runtime
    ports:
      - "8080:8080"
    volumes:
      # Mount source code
      - ./src:/var/www/html/src
      - ./config:/var/www/html/config
      - ./public:/var/www/html/public
    environment:
      APP_ENV: dev
      APP_DEBUG: 1
      DATABASE_URL: postgresql://symfony:symfony@db:5432/symfony?serverVersion=15&charset=utf8
    depends_on:
      - db
    networks:
      - symfony-network

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: symfony
      POSTGRES_USER: symfony
      POSTGRES_PASSWORD: symfony
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - symfony-network

volumes:
  db-data:

networks:
  symfony-network:
    driver: bridge